site_name: EW-Origin

nav:
    - Introduction: index.md
    - Getting started: getting-started.md
    - Architecture: architecture.md
    - Packages: packages.md
    - User guides:
          - Glossary: user-guide-glossary.md
          - Onboarding and Registration: user-guide-reg-onboarding.md
          - Device Management: user-guide-device-management.md
          - Organization Management: user-guide-organization.md
          - Using the Exchange: user-guide-exchange.md
    - Configuration:
          - UI: configuration-ui.md
    - SDK:
          - Traceability: traceability.md
          - Trade: trade.md
          - Device Registry: device-registry.md
          - Organizations: organizations.md
    - SDK Reference:
          - '@energyweb/issuer-irec-api-wrapper': sdk-reference/issuer-irec-api-wrapper/modules.md
    - Cookbook:
          - How to deploy to Volta: volta-deployment.md
          - Run with Docker: docker.md

theme:
    name: material
    logo: images/EWF-EWBrandmark-Knockout.png
    palette:
        primary: black
repo_url: https://github.com/energywebfoundation/origin

plugins:
    - mermaid2
    - search
    - autolinks

extra_javascript:
    - https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js
